#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-rpath \
    --without-libcap \
    --disable-pinentry-curses \
    --disable-pinentry-emacs \
    --disable-pinentry-gtk2 \
    --disable-pinentry-gnome3 \
    --disable-pinentry-qt \
    --enable-pinentry-tty

make
make DESTDIR="$1" install
